[package]
name = "rpc-block-crawler-datasource"
version.workspace = true
edition.workspace = true
publish.workspace = true
autotests = false
readme = "README.md"

[dependencies]
tracing.workspace = true
raven-engine.workspace = true
raven-evm.workspace = true
alloy-rpc-types-eth = { workspace = true, features = ["serde"] }
async-trait.workspace = true
thiserror.workspace = true
serde.workspace = true
alloy-provider.workspace = true
alloy-transport.workspace = true
tokio = { workspace = true, features = ["macros", "rt", "time"] }

[dev-dependencies]
serde_json.workspace = true
tokio = { workspace = true, features = [
	"macros",
	"rt",
	"time",
	"net",
	"io-util",
	"test-util",
] }

[[test]]
name = "crawler"
path = "tests/crawler.rs"

[[test]]
name = "runtime"
path = "tests/runtime.rs"
