[package]
name = "graph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-trait = "0.1.52"
diesel = { version = "1.4.8", features = ["postgres", "serde_json", "numeric", "r2d2", "chrono"] }
diesel_derives = "1.4"

ethabi = "17.1.0"

thiserror = "1.0"
hex = "0.4.3"
web3 = { git = "https://github.com/graphprotocol/rust-web3", branch = "lutter/graph-0.15.0", features = ["arbitrary_precision"] }
atty = "0.2.0"

serde = { version = "1.0.135", features = ["rc"] }
serde_derive = "1.0.135"
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
serde_yaml = "0.8"
# serde_plain = "1.0.0"

slog = { version = "2.7.0", features = ["release_max_level_trace", "max_level_trace"] }
slog-async = "2.7.0"
slog-term = "2.8.0"

url = "2.2.1"
http = "0.2.5"
lazy_static = "1.4.0"
tokio = { version = "1.15.0", features = ["full"] }
tokio-stream = { version = "0.1.9", features = ["sync"] }
tokio-retry = "0.3.0"

parking_lot = "0.11.2"

futures = "0.1.31"
futures03 = { version = "0.3.21", package = "futures", features = ["compat"] }