[package]
name = "raven-evm"
version.workspace = true
edition.workspace = true
publish.workspace = true
autotests = false

[dependencies]
raven-engine.workspace = true
alloy-primitives.workspace = true
alloy-sol-types.workspace = true
alloy-rpc-types-eth.workspace = true
async-trait.workspace = true
thiserror.workspace = true

[dev-dependencies]
alloy-consensus.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }

[[test]]
name = "filters"
path = "tests/filters.rs"

[[test]]
name = "updates"
path = "tests/updates.rs"

[[test]]
name = "parsers"
path = "tests/parsers.rs"

[[test]]
name = "pipeline"
path = "tests/pipeline.rs"
